### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [mschlauch/comfortreader#15]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate either here or via email, so I don't have to create issues. Thank you.

**Comment by mschlauch** [comment]
Hello Hamzeto938,
I am more than happy to receive your contributions. Help is very needed - as you can see, I'm rather behind with updating app descriptions and writing a decent FAQ (https://raw.githubusercontent.com/mschlauch/comfortreader/master/FAQ.txt). It seems to me that as a developer I'm oftentimes missing the user perspective - so it's actually a good thing to get some input from a non-developer. Feel free to communicate here or via the e-mail address published on my website: http://comfortreader.rhizomaticdesign.net/en/
Thanks

**Comment by Hamzeto938** [comment]
okay, if so can i help out with the FAQs from a users  perspective and also an ABOUT US

**Comment by mschlauch** [comment]
That would be great. I'm hopeful, especially with the FAQ from a user perspective. Let me know if you need more information.

**Comment by mschlauch** [comment]
Nothing happened, I'm closing this issue.
