### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [mschlauch/comfortreader#16]
Hello, @mschlauchI want to contribute in "comfortreader" so i  want to designed a new logo for "comfortreader" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary

**Comment by mschlauch** [comment]
Thank you! I highly appreciate it (just saw your great work with the weather app :+1:). Could you post a preview of your first general idea here? Then we could work it out right here so that others are able to follow the whole process, too. That would be fantastic.

**Comment by abdulmalikkhan655** [comment]
Thank you very much for your encouragement and soon I will send you log preview  of your  application

**Comment by ggcarlosr** [comment]
Hello friend, I am also available to join by presenting a logo proposal, and you can have a second option to choose, can I contribute?

**Comment by mschlauch** [comment]
Sure. The more ideas, the better. If not as a logo, an additional graphical representation of the app can still be used in plenty of ways (I was thinking about a splash screen maybe, headers, descriptions...).

**Comment by ggcarlosr** [comment]
perfect you could give me an introduction that treats your app?

**Comment by abdulmalikkhan655** [comment]
hello sir check this logo and select your logo If there's something you want to change, I'll do it. 
![11](https://user-images.githubusercontent.com/36396753/39964800-11bd2584-56a6-11e8-8aee-136ede7b12ab.jpg)
![22](https://user-images.githubusercontent.com/36396753/39964801-11f87256-56a6-11e8-91c1-304fa9d6d4d7.jpg)
![33](https://user-images.githubusercontent.com/36396753/39964802-1236a7ce-56a6-11e8-914d-efb59d2f0b2a.jpg)
![44](https://user-images.githubusercontent.com/36396753/39964803-127409de-56a6-11e8-93f8-70edf05a82c1.jpg)

**Comment by mschlauch** [comment]
I think logo 5 (cup of coffee/tea) is a good starting point. Let's wait for the other proposal and see how to move on. @ggcarlosr I once made an introduction video https://youtu.be/j8faET-o8XI and there is the website comfortreader.rhizomaticdesign.net 
The point I tried to make is that reading with comfortreader is much like "watching a film" (with subtitles) or that your device "speaks" (streams) a text more directly to your eyes (as you don't have to turn pages and move your eyes around anymore).

**Comment by abdulmalikkhan655** [comment]
@mschlauch  thanks for  select logo number 5

I would tell you for your information @ggcarlosr  is scammer , he is not a designer . This person follows my all  post and gives it the same comments   but  they cannot show the log design I think it will be the loss of our time waiting for it . Because I have not yet seen that he has given  the any logo  designs

**Comment by mschlauch** [comment]
I have to say that I don't quit understand why one should do so, is it something about utopian.io? Well anyhow, if ggcarlosr wants to, he's still free to contribute. But if you want to go further, I'm interested to see how you would insert the idea of a device that "beams up" a text/book (as in the current logo) instead of a person holding only newspaper. As automation+comfort in reading is another central aspect of the app.

**Comment by abdulmalikkhan655** [comment]
![dfsd](https://user-images.githubusercontent.com/36396753/39970203-10e114e4-5701-11e8-871d-4aa90d8dc5c9.png)
![sdfas](https://user-images.githubusercontent.com/36396753/39970204-111aa4f2-5701-11e8-831b-cf7f88fafe74.png)

Hello Dear
I try to make logo as you said i hope you will like this and i can more change in these if you want any thing more and now let you know about @ggcarlosr i cant bet he will never send you any logo because i already see many posts 20+ with his same message and i never see any logo which he make and share so i done my work now you can wait for @ggcarlosr i have no any problem i just tell you and i can also share link where he already spamming if you want to check 
Thank You

**Comment by TacoTheDank** [comment]
@mschlauch just so you know, adbulmalikkhan655 himself is kinda a scammer, since he gets all his icons from flaticons and other icon sites and passes them off as his own

read https://github.com/kaeptmblaubaer1000/android-torchlight/issues/3

**Comment by abdulmalikkhan655** [comment]
scamer

**Comment by TacoTheDank** [comment]
yep, you sure are

**Comment by mschlauch** [comment]
@TacoTheDank thanks for your advise and the link. I see this is not the only occurrence of this strange phenomenon.
