### ISSUE TITLE
FAQs document creation

### ISSUE THREAD

**Issue by HarryHeights** [mschlauch/comfortreader#18]
Hello. I'm Harry. 
I could help write the FAQs if you still need it. 
Helping developers create written texts is my way of supporting and contributing to open source projects. If you give the go ahead, I'll create the text file immediately and make a pull request. 
You can check out my profile for my contributions to other projects too.  If you also need a privacy policy document created, I could do that also.

**Comment by mschlauch** [comment]
https://github.com/mschlauch/comfortreader/pull/19
